### ISSUE TITLE
`docs/data/non-imdb-movie-reviews` does not exist?!

### ISSUE THREAD

**Issue by OmaymaS** [rstudio-conf-2020/dl-keras-tf#2]
I can see `docs/data/non-imdb-movie-reviews` does not exist in the repo. And I couldn't see it created in the `requirements.Rmd`. Am I missing sth?

https://github.com/rstudio-conf-2020/dl-keras-tf/blob/fdbc8b0b2602eddf4f0caede32526a5d6a2b469a/materials/06-word-embeddings/04-pretrained-non-IMDB-word-embeddings.Rmd#L16

**Comment by bradleyboehmke** [comment]
Good catch. I had a couple files in the embeddings folder that I was undecided on. I deleted a couple unnecessary files with (eea697c)[https://github.com/rstudio-conf-2020/dl-keras-tf/commit/eea697ce8c8b6cf5393f16a738a29b0be6db3c7e] and moved/renamed this non-IMDB file to the LSTM folder, which is where I'll present it if I decide to. For now I added a note at the top of the file marking it as incomplete. If I keep it I'll add the proper requirement pipeline in requirements.Rmd.
